### ISSUE TITLE
Add a way to customize download folder from UI

### ISSUE THREAD

**Issue by mohammadrafigh** [Caleb9/downloader#1]
It would be great if we could also choose or create a subfolder from the UI to download file into it.
For example I want to download `a.mp4` in a specific subfolder folder which could be different for 'b.mp4'.
I understand that might make problems if you want to allow downloading to all filesystem directories but it would be safe to allow users modify nested directories from the specified download location.

**Comment by Caleb9** [comment]
Hi @mohammadrafigh, thanks for your suggestion. Making a UI for something like this would probably take some effort. How about, for starers, you could type a relative path into the "Save as" box? E.g. `folder1/folder2/a.mp4` would create the folders if they didn't exist already. That would be an easy thing to implement I think.

**Comment by mohammadrafigh** [comment]
Yeah I was actually looking for something like that. It would be great.

**Comment by Caleb9** [comment]
Let me see what I can do in the coming days :)

**Comment by mohammadrafigh** [comment]
Great. Thank you

**Comment by Caleb9** [comment]
@mohammadrafigh try the latest image. Please let me know if you find any problems. Also, you're welcome to give the project a star if you like it ;). Cheers.

**Comment by mohammadrafigh** [comment]
Thank you. starred! I could help more if I knew C# :smile: I used to develop using C# 10 years ago. But I might be able to help in some parts of frontend. Soon I will add a new feature request to add a minimal authentication to prevent everyone upload to server.

**Comment by Caleb9** [comment]
Yeah I could really use some help in the front-end - look how ugly it looks ;D. My React and CSS skills are pretty basic. If you fork it then I would welcome PRs back :)

**Comment by mohammadrafigh** [comment]
I works like a charm. Thank you
